version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "3005:80"
    volumes:
      - ./public:/var/www/public
      - ./app:/var/www/app
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./public:/var/www/public
      - ./app:/var/www/app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_crud
    volumes:
      - ./db/db_crud.sql:/docker-entrypoint-initdb.d/db_crud.sql
